# Generated by Django 4.1.1 on 2022-12-01 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomapp', '0003_addroom_room_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addroom',
            name='photo',
        ),
        migrations.AddField(
            model_name='addroom',
            name='image',
            field=models.ImageField(default='s', upload_to='images/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='addroom',
            name='rate',
            field=models.CharField(max_length=100, verbose_name='rate'),
        ),
        migrations.AlterField(
            model_name='addroom',
            name='room_type',
            field=models.CharField(max_length=20, verbose_name='roomtype'),
        ),
    ]
