# Generated by Django 4.1.1 on 2022-12-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomapp', '0004_remove_addroom_photo_addroom_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addroom',
            name='discription',
            field=models.CharField(max_length=25, verbose_name='discription'),
        ),
        migrations.AlterField(
            model_name='addroom',
            name='room_name',
            field=models.CharField(max_length=100, verbose_name='room_name'),
        ),
        migrations.AlterField(
            model_name='addroom',
            name='room_type',
            field=models.CharField(max_length=20, verbose_name='room_type'),
        ),
    ]
