# Generated by Django 4.1.1 on 2022-12-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomapp', '0005_alter_addroom_discription_alter_addroom_room_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addroom',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='image'),
        ),
    ]
