# Generated by Django 4.1.1 on 2022-12-02 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomapp', '0006_alter_addroom_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='usertype',
            field=models.CharField(default='s', max_length=25),
        ),
    ]
