# Generated by Django 4.1.2 on 2022-12-07 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomapp', '0007_registration_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='addroom',
            name='phone',
            field=models.IntegerField(default=1, max_length=10),
        ),
    ]
