# Generated by Django 4.1.2 on 2022-12-07 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomapp', '0008_addroom_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addroom',
            name='phone',
            field=models.IntegerField(max_length=10),
        ),
    ]
