# Generated by Django 4.1.2 on 2022-12-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomapp', '0011_alter_addroom_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addroom',
            name='id',
        ),
        migrations.AlterField(
            model_name='addroom',
            name='room_id',
            field=models.IntegerField(primary_key='True', serialize=False),
        ),
    ]
