# Generated by Django 4.1.2 on 2022-12-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomapp', '0012_remove_addroom_id_alter_addroom_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addroom',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
