# Generated by Django 4.1.2 on 2022-12-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomapp', '0013_alter_addroom_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='addroom',
            name='id',
            field=models.IntegerField(default=1),
        ),
    ]
