# Generated by Django 4.1.2 on 2022-12-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomapp', '0014_addroom_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addroom',
            name='id',
            field=models.IntegerField(),
        ),
    ]
